services:
  cat_tracker:
    container_name: cat_tracker
    depends_on:
      - cat_postgres
      - cat_bitcoind
    restart: always
    env_file:
      - .env
    environment:
      - VIRTUAL_HOST=cat.mydapp.io
      - VIRTUAL_PORT=4000
      - LETSENCRYPT_HOST=cat.mydapp.io
      - LETSENCRYPT_EMAIL=lilong@gmail.com
    build:
      context: ./
      args:
        - FILE=.env
    working_dir: /app/apps/tracker
    command: pnpm start:prod
    volumes:
      - ./docker/logs/tracker:/app/logs
    ports:
      - "4000:4000"

  cat_postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: $DATABASE_USERNAME
      POSTGRES_PASSWORD: $DATABASE_PASSWORD
      POSTGRES_DB: $DATABASE_DB
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "6432:5432"
    volumes:
      - ./docker/pgdata:/var/lib/postgresql/data

  cat_bitcoind:
    image: fractalbitcoin/fractal:v0.2.1
    restart: always
    entrypoint: ["bitcoind", "-datadir=/data/", "-maxtipage=504576000"]
    command: ""
    healthcheck:
      test: ["CMD", "bitcoin-cli", "-datadir=/data/", "getblockchaininfo"]
    ports:
      - "9330:8330"
      - "9331:8331"
      - "9332:8332"
      - "9333:8333"
    deploy:
      resources:
        limits:
          memory: 40G
    memswap_limit: 60G
    mem_swappiness: 100
    volumes:
      - ./docker/data:/data
    logging:
      driver: "json-file"
      options:
        labels: "env,filebeat,name"
        max-size: "1g"
        max-file: "3"

networks:
  default:
    name: shared
    external: true
